#!/usr/bin/tcsh
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task 1
#SBATCH --mem-per-cpu 16G
#SBATCH --error=/home/petrosp/Lab2/output/error.out
#SBATCH --output=/home/petrosp/Lab2/output/output.out

module load GCC/9.3.0
module  load VTune/2021.6.0

# rm -fr output
# mkdir output
# gcc -Wall -Werror -p Lab2_SimpleLoop_std.c





cat /sys/class/powercap/intel-rapl/intel-rapl\:0/energy_uj > power.out
cat /sys/class/powercap/intel-rapl/intel-rapl\:1/energy_uj >> power.out
./a.out
cat /sys/class/powercap/intel-rapl/intel-rapl\:0/energy_uj >> power.out
cat /sys/class/powercap/intel-rapl/intel-rapl\:1/energy_uj >> power.out

lscpu > cpuinfo.out

vtune -r output -collect hotspots -- ./a.out
vtune -report summary -r output > vTune.out
vtune -report hotspots -r output >> vTune.out
vtune -report callstacks -r output >> vTune.out
vtune -report top-down -r output >> vTune.out
vtune -report gprof-cc -r output >> vTune.out
vtune -report hw-events -r output >> vTune.out
